### ISSUE TITLE
Add a contact us form

### ISSUE THREAD

**Issue by saracope** [gdidayton/gdidayton.com#7]

**Comment by bryanbraun** [comment]
Hey @saracope, since this is a static site, do you have a service in mind? I've used https://formspree.io, which is pretty basic... just forwarding responses to an email address. It's free for low submission volumes.

Happy to put in a PR if you want to go that route.

Also, would you want it on an existing page, or a new "contact" page?

**Comment by kcjonesevans** [comment]
@bryanbraun I believe the that idea was to have it be a new page. Go ahead and submit a PR and I can review it.

**Comment by saracope** [comment]
@bryanbraun: I was thinking of using a Google Form since that's what we use as a team already. Thinking of something simple like capturing Name, Email, Comment. Then also include our team email (dayton@girldevelopit.com) if anyone wants to just email directly.

Yes, should be a new page. Contact seems easy and fine with me. 

Thoughts @k80bowman and @kcjonesevans?

**Comment by kcjonesevans** [comment]
Contact form needs to be accessible by someone with the girldevelopit domain

**Comment by saracope** [comment]
Link to new form in GDI domain: https://docs.google.com/forms/d/e/1FAIpQLSdHItOWdmcNNKyAuRw1f1V5ovvZMdJk3qqCxjpMuyTNkIkJdQ/viewform

**Comment by saracope** [comment]
Attaching form data for linking in the Jekyll config.

<img width="361" alt="screen shot 2016-10-27 at 12 11 40 pm" src="https://cloud.githubusercontent.com/assets/2197515/19775529/ae819a7c-9c3e-11e6-9d44-ab2119799ba1.png">

**Comment by bryanbraun** [comment]
Linking in the Jekyll config? What do you have in mind?
