### ISSUE TITLE
Fix hero image/header responsive views

### ISSUE THREAD

**Issue by k80bowman** [gdidayton/gdidayton.com#94]
600px:
![image](https://user-images.githubusercontent.com/12739849/40632688-a63850f4-62b7-11e8-980f-3cedfb0e2cda.png)

679px:
![image](https://user-images.githubusercontent.com/12739849/40632698-b92001ee-62b7-11e8-9c28-4a0be1a65af5.png)

900px:
![image](https://user-images.githubusercontent.com/12739849/40632707-ce90225c-62b7-11e8-9f42-e2fa7c298cef.png)

**Comment by zastrow** [comment]
I’ll pick this one up.

**Comment by kcjonesevans** [comment]
@zastrow we are in the process of a Nation rebranding. The new tagline will be "Code, Confidence and Community". I'd appreciate any creative changes to the hero image using the new phrase.

**Comment by zastrow** [comment]
@kcjonesevans Can Do! Seems like the biggest problem with this particular issue the navigation on certain screen sizes, so that’ll be my primary focus first. On other pages at that 679px screen size the navigation is white text on a white background.

Then the tagline needs some adjustments to keep it from breaking down like it does. I will add in the new text though.

**Comment by kcjonesevans** [comment]
I noticed the navigation scss/media query was a bit weird myself when I was fixing the hover in another issue https://github.com/gdidayton/gdidayton/pull/111
